# Site Settings
name: "Star Jelly"
title: "Star Jelly"
email: ejr255@gmail.com
description: >-
  Ethan Rodriguez's Art Porfolio.
baseurl: "/star-jelly"
url: ""
twitter_username: starjelly13
github_username: ejr255

# Build Settings
markdown: kramdown
highlighter: pygments

# Not Used
#permalink: /star-jelly/:year/:month/:day/:title
#exclude: ['.git']
