highlighter: pygments
permalink: /star-jelly/:year/:month/:day/:title
markdown: kramdown
exclude: ['.git']
name: "Star Jelly"
description: "Ethan Rodriguez's Art Portfolio"
#url: http://cdr255.com
twitter: starjelly13